import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"])

import {  Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})


export const metadata = {
  title: "PawsNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${poppins.className} bg-[#f5ede0]`}>

        {children}

      </body>
    </html>
  );
}
